language: csharp
solution: "KountSdk.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" KountSdk.sln
script:
- xbuild KountSdk.sln
- mono KountRisTest/packages/xunit.runner.console*/tools/xunit.console.exe KountRisTest/bin/Debug/KountRisTest.Tests.dll
